name: neuro
channels:
  - pytorch
  - defaults
dependencies:
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cpuonly=2.0
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.55.3
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=308
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scipy=1.15.2
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - alembic==1.15.2
      - astunparse==1.6.3
      - colorlog==6.9.0
      - coverage==7.8.0
      - edfio==0.4.8
      - edflib-python==1.0.8
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fsspec==2025.3.2
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.2
      - grpcio==1.71.0
      - h5py==3.13.0
      - keras==3.9.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - ml-dtypes==0.5.1
      - mne==1.9.0
      - mne-bids==0.16.0
      - moabb==1.2.0
      - namex==0.0.8
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.15.0
      - optuna==4.3.0
      - pooch==1.8.2
      - protobuf==5.29.4
      - pyedflib==0.1.40
      - pyriemann==0.7
      - rich==14.0.0
      - scikit-learn==1.5.2
      - seaborn==0.12.2
      - sqlalchemy==2.0.41
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.0.1
      - torch==2.7.0
      - tqdm==4.67.1
      - urllib3==1.26.20
      - werkzeug==3.1.3
      - wrapt==1.17.2
prefix: C:\Users\spiro\anaconda3\envs\neuro
